name: GitHub Actions - Create Infrastructure
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
                
      - name: Initialize Backend
        working-directory: backend
        run: |
          echo "Initializing backend..."
          terraform init .