name: GitHub Actions - Initialize Backend
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
                
      - name: Initialize Backend
        working-directory: backend
        run: |
          echo "Initializing backend..."
          terraform init
          terraform plan
          terraform apply -auto-approve
          echo "Backend initialized successfully."
      
      - name: Print output
        working-directory: backend
        run: |
          echo "Terraform Backend:"
          terraform output -json | jq -r '.backend.value'